# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  pull_request:
    branches: ["main"]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Build and check distributions
      run: |
        python -m pip install build twine
        python -m build
        python -m twine check dist/*
        ls -lh dist/
    - name: Verify wheel and source distribution
      run: |
        python -m pip install dist/*.whl
        pushd /tmp
        python -c "import importlib.metadata as m, os; from pathlib import Path; import torch_linear_assignment as p; assert m.version('torch-linear-assignment') == '0.1.0'; assert not Path(p.__file__).resolve().is_relative_to(Path(os.environ['GITHUB_WORKSPACE']).resolve()); print(p.__file__)"
        popd
        python -m pip uninstall -y torch-linear-assignment
        python -m pip install --no-deps dist/*.tar.gz
        pushd /tmp
        python -c "import importlib.metadata as m, os; from pathlib import Path; import torch_linear_assignment as p; assert m.version('torch-linear-assignment') == '0.1.0'; assert not Path(p.__file__).resolve().is_relative_to(Path(os.environ['GITHUB_WORKSPACE']).resolve()); print(p.__file__)"
        popd

    - name: Publish package
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
